return {
  -- "romgrk/barbar.nvim",
  -- -- event = 'VeryLazy', -- TODO bar shown at start
  -- dependencies = {
  --   "lewis6991/gitsigns.nvim",
  --   "nvim-tree/nvim-web-devicons",
  -- },
  -- opts = {
  --   auto_hide = true,
  --   icons = {
  --     filetype = {
  --       enabled = false,
  --     },
  --     separator = {
  --       left = '',
  --     }
  --   }
  -- },
  -- init = function()
  --   vim.g.barbar_auto_setup = false
  -- end,
}
