return {
  "tpope/vim-fugitive",
  dependencies = { "tpope/vim-rhubarb" },  -- GitHub :GBrowse support
  cmd = {
    "G",
    "GBrowse",
    "Gcd",
    "Gclog",
    "GDelete",
    "Gdiffsplit",
    "Gdrop",
    "Gedit",
    "Ggrep",
    "Ghdiffsplit",
    "Git",
    "Glcd",
    "Glgrep",
    "Gllog",
    "GMove",
    "Gpedit",
    "Gread",
    "GRemove",
    "GRename",
    "Gsplit",
    "Gtabedit",
    "GUnlink",
    "Gvdiffsplit",
    "Gvsplit",
    "Gwq",
    "Gwrite",
  },
}
