return {
  -- "folke/noice.nvim",
  -- opts = {
  --   cmdline = {
  --     format = {
  --       cmdline = {
  --         title = ""
  --       }
  --     }
  --   },
  --   lsp = {
  --     override = {
  --       ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
  --       ["vim.lsp.util.stylize_markdown"] = true,
  --       ["cmp.entry.get_documentation"] = true,
  --     },
  --   },
  --   presets = {
  --     bottom_search = true,
  --     command_palette = false,
  --     long_message_to_split = true,
  --   },
  --   routes = {
  --     {
  --       view = 'mini',
  --       filter = {
  --         event = 'msg_show',
  --         kind = '',
  --         find = 'written',
  --       },
  --       opts = {},
  --     },
  --     {
  --       filter = {
  --         event = 'lsp',
  --         kind = 'progress',
  --         cond = function(message)
  --           local title = vim.tbl_get(message.opts, 'progress', 'title')
  --           local client = vim.tbl_get(message.opts, 'progress', 'client')

  --           return client == 'null-ls' and title == 'code_action'
  --         end,
  --       },
  --       opts = { skip = true },
  --     },
  --   },
  -- },
  -- dependencies = {
  --   "MunifTanjim/nui.nvim",
  --   {
  --     "rcarriga/nvim-notify",
  --     opts = {
  --       render = "compact",
  --       stages = "fade",
  --     }
  --   },
  -- },
  -- event = "VeryLazy",
}
